#!/bin/bash

./orchestration/run sunsh 20 ../official/data/dnsmitm-with-json       dnsmitm
./orchestration/run sunsh 20 ../official/data/packetsniffer-with-json packetsniffer
./orchestration/run sunsh 20 ../official/data/portscanner-with-json   portscanner
./orchestration/run sunsh 20 ../official/data/ransomware-with-json    ransomware
./orchestration/run sunsh 20 ../official/data/spread-with-json        spread
./orchestration/run sunsh 20 ../official/data/synflood-with-json      synflood
./orchestration/run sunsh 20 ../official/data/upload-with-json        upload

cd ../official && git add * && git commit -m "re-running all the data" && git push

